import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/CartContext";
import { ToastContainer } from "react-toastify";
import QueryClientProviderWrapper from "./QueryClientProviderWrapper";
import TawkScript from "@/scripts/TawkScript";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Commercetools Checkout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <QueryClientProviderWrapper>
          <CartProvider>
            <ToastContainer />
            <Header />
            <div className="pb-16 flex flex-1 items-center justify-center">
              {children}
            </div>
            <div className="fixed bottom-0 w-full">
              <Footer />
            </div>
          </CartProvider>
        </QueryClientProviderWrapper>
        <TawkScript />
      </body>
    </html>
  );
}
